# Generated by Django 4.2.6 on 2023-10-31 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseplanninganalysisdata',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseplanninganalysisdata',
            name='cabinet',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaseplanninganalysisdata',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='purchaseplanninganalysisdata',
            name='product',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaseplanninganalysisdata',
            name='wb_warehouse',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
