# Generated by Django 4.2.6 on 2023-10-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_alter_purchaseplanninganalysisdata_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseplanninganalysisdata',
            name='cabinet',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='purchaseplanninganalysisdata',
            name='product',
            field=models.IntegerField(blank=True),
        ),
    ]
