# Generated by Django 4.2.6 on 2023-10-31 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0003_alter_purchaseplanninganalysisdata_cabinet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseplanninganalysisdata',
            name='brand',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseplanninganalysisdata',
            name='cabinet',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseplanninganalysisdata',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseplanninganalysisdata',
            name='product',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='purchaseplanninganalysisdata',
            name='wb_warehouse',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
